version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-cache-{{ .Branch }}-{{ checksum "composer.json" }}
      - run: composer install --prefer-dist
      - save_cache:
          key: composer-cache-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - "~/.composer/cache"
      - run: composer ci
